### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by ghost** [russells/process-monitor#1]
is there any more document?

有文档吗，大哥。

**Comment by russells** [comment]
On Thu, Mar 23, 2017 at 01:13:16AM -0700, ruimaj wrote:
> is there any more document?

No.


> 
> 有文档吗，大哥。
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/russells/process-monitor/issues/1


-- 
Russell Steicke

**Comment by ghost** [comment]
OK
